#!/bin/bash
#./c 'file_to_create'
echo '#!/bin/bash' > $1
echo 'File created: ' $1
echo 'File executable.'; chmod u+x $1
echo 'Number of lines of the file: '; wc -l $1
echo 'Header of the file: '; head -n 1 $1
echo 'Execution result: '
./$1
